[
  {
    "id": "download-stream",
    "execute-command": "/opt/ffmpeg-webhook/scripts/download-stream.sh",
    "command-working-directory": "/tmp",
    "response-message": "Download started",
    "pass-arguments-to-command": [
      {
        "source": "payload",
        "name": "url"
      },
      {
        "source": "payload",
        "name": "name"
      }
    ]
  }
]
